---
name: "MediaTracker"
guid: "c4772eae-799e-490d-abff-4de21f99c95e"
version: "2.0.0.1"
targetAbi: "10.9.1.0"
framework: "net8.0"
overview: "MediaTracker scrobbler"
description: "MediaTracker scrobbler"
category: "General"
owner: "bonukai"
artifacts:
- "Jellyfin.Plugin.MediaTracker.dll"
changelog:
- "refactored ShouldSkipAction"
