---
name: "MediaTracker"
guid: "c4772eae-799e-490d-abff-4de21f99c95e"
version: 1
targetAbi: "10.8.9.0"
framework: "net6.0"
overview: "MediaTracker scrobbler"
description: "MediaTracker scrobbler"
category: "General"
owner: "bonukai"
artifacts:
- "Jellyfin.Plugin.MediaTracker.dll"
changelog:
